# Generated by Django 3.2.5 on 2021-07-21 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HelloWordl',
            new_name='HelloWorld',
        ),
    ]
