# Generated by Django 3.2.5 on 2021-07-21 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_rename_hellowordl_helloworld'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helloworld',
            old_name='test',
            new_name='text',
        ),
    ]
